@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            
            <div class="card">
                <div class="card-header">{{ __('Informavimas apie orų kaitą') }}</div>

                <div class="card-body">
                    <form action="{{ route('informForecast') }}" method="post" name="inform">
                        @csrf
                          
                        @if (session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @endif
	
                        @if (session('error'))
                            <div class="alert alert-danger">
                                {{ session('error') }}
                            </div>
                        @endif
                        
                        {{--<div class="form-group">
                            <label>Regionas</label>
                            
                            <select class="form-control" name="aaaa" required>
                                <option value="" selected="true" disabled="disabled">Pasirinkite regioną</option>
                                <option value="vilnius">Vilnius</option>
                                <option value="kaunas">Kaunas</option>
                                <option value="klaipeda">Klaipėda</option>
                                <option value="siauliai">Šiauliai</option>
                                <option value="panevezys">Panevėžys</option>
                            </select>
            
                        </div>--}}

                        <div class="form-group">
                            <label> <strong>Pasirinkite regioną paspausdami žemėlapyje ant norimo regiono </strong></label>

                            <img src="{{ URL('/images/lithuania4.png') }}" usemap="#image-map">
                            <!-- Image Map Generated by http://www.image-map.net/ -->

                            <map name="image-map" id="image-map">
                                <area target="" alt="Vilnius" title="Vilnius" href="#" onclick="javascript:document.inform.region.value='vilnius'; javascript:document.inform.display.value='Vilnius'; return true" coords="349,251,44" shape="circle">
                                <area target="" alt="Kaunas" title="Kaunas" href="#" onclick="javascript:document.inform.region.value='kaunas'; javascript:document.inform.display.value='Kaunas'; return true" coords="261,203,44" shape="circle">
                                <area target="" alt="Klaipdėda" title="Klaipdėda" href="#" onclick="javascript:document.inform.region.value='klaipeda'; javascript:document.inform.display.value='Klaipdėda'; return true" coords="70,131,38" shape="circle">
                                <area target="" alt="Šiauliai" title="Šiauliai" href="#" onclick="javascript:document.inform.region.value='siauliai'; javascript:document.inform.display.value='Šiauliai'; return true" coords="209,92,42" shape="circle">
                                <area target="" alt="Panevėžys" title="Panevėžys" href="#" onclick="javascript:document.inform.region.value='panevezys'; javascript:document.inform.display.value='Panevėžys'; return true" coords="313,101,43" shape="circle">
                            </map>
                            

                            <label> Pasirinktas regionas </label>
                            <input type="hidden" class="form-control" name="region" value="" />
                            <input type="text" class="form-control @error('region') is-invalid @enderror" name="display" value="Nėra pasirinkto regiono" disabled="disabled" />
                            @error('region')
                                <span class="invalid-feedback" role="alert">
                                    <strong> Reikia žemėlapyje pasirinkti regioną </strong>
                                </span>
                            @enderror

                        </div>


                        
                        <div class="form-group">
                            <label> <strong>Pageidaujamas vėjo stiprumas (m/s) </strong> </label>
                            <br>
                            <label>Pirmas pageidavimas</label>
                            <div class="form-row">
                                
                                <div class="col">
                                    <input type="number" class="form-control @error('windSpeed1') is-invalid @enderror" name="windSpeed1" value="{{ old('windSpeed1') }}">

                                    @error('windSpeed1')
                                        <span class="invalid-feedback" role="alert">
                                            <strong> Reikia nurodyti norimą vėjo stiprumą </strong>
                                        </span>
                                    @enderror

                                </div>

                                <div class="col">
                                    <div class="form-check form-check-inline @error('windSpeedTrend1') is-invalid @enderror">
                                        <input class="form-check-input" type="radio" name="windSpeedTrend1" id="windSpeedTrend11" value="less" checked>
                                        <label class="form-check-label" for="windSpeedTrend11"> Mažiau </label>
                                    </div>
                                    <div class="form-check form-check-inline @error('windSpeedTrend1') is-invalid @enderror">
                                        <input class="form-check-input" type="radio" name="windSpeedTrend1" id="windSpeedTrend12" value="more">
                                        <label class="form-check-label" for="windSpeedTrend12"> Daugiau </label>
                                    </div>
                                    @error('windSpeedTrend1')
                                        <span class="invalid-feedback" role="alert">
                                            <strong> Reikia nurodyti pageidaujamo vėjo stiprumo kryptį </strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <br>
                            <label>Antras pageidavimas (nebūtinas)</label>
                            <div class="form-row">
                                
                                <div class="col">
                                    <input type="number" class="form-control" name="windSpeed2" value="{{ old('windSpeed2') }}">

                                    @error('windSpeed2')
                                        <span class="invalid-feedback" role="alert">
                                            <strong> Reikia nurodyti norimą vėjo stiprumą </strong>
                                        </span>
                                    @enderror

                                </div>

                                <div class="col">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="windSpeedTrend2" id="windSpeedTrend21" value="less">
                                        <label class="form-check-label" for="windSpeedTrend21"> Mažiau </label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="windSpeedTrend2" id="windSpeedTrend22" value="more">
                                        <label class="form-check-label" for="windSpeedTrend22"> Daugiau </label>
                                    </div>
                                </div>
                            </div>
                            
                        </div>

                        {{--<div class="form-group">
                            <label>Pageidaujate mažesnio ar didesnio vėjo stiprumo nei nurodėte</label>
                            <select class="form-control" name="windSpeedTrend" required>
                                <option value="">Pasirinkite vėjo stiprumą</option>
                                <option value="daugiau">Daugiau</option>
                                <option value="maziau">Maziau</option>
                            </select>
                        </div>--}}
                        <button type="submit" class="btn btn-primary"> Vykdyti </button>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
